# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['backend/app/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('data/app.dev-copy.db', 'data'),
    ],
    hiddenimports=[
        'backend.app.models',
        'backend.app.models.user',
        'backend.app.models.question',
        'backend.app.models.record',
        'backend.app.models.achievement',
        'backend.app.models.pvp',
        'backend.app.models.unit',
        'backend.app.routers',
        'backend.app.routers.auth',
        'backend.app.routers.units',
        'backend.app.routers.questions',
        'backend.app.routers.records',
        'backend.app.routers.scores',
        'backend.app.routers.achievements',
        'backend.app.routers.leaderboard',
        'backend.app.routers.pvp',
        'backend.app.routers.admin',
        'backend.app.services',
        'backend.app.services.auth_service',
        'backend.app.services.question_service',
        'backend.app.services.scoring_service',
        'backend.app.services.pvp_service',
        'backend.app.services.rate_limiter',
        'backend.app.ws',
        'backend.app.ws.manager',
        'backend.app.ws.router',
        'backend.app.ws.auth_cache',
        'backend.app.schemas',
        'backend.app.schemas.auth',
        'backend.app.schemas.question',
        'backend.app.schemas.record',
        'backend.app.schemas.pvp',
        'backend.app.schemas.admin',
        'passlib.handlers.bcrypt',
        'passlib.handlers',
        'passlib.utils',
        'passlib.utils.handlers',
        'bcrypt',
        'openpyxl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['psycopg2', 'psycopg2-binary'],
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PythonAdventure80-OneFile',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_tracked=False,
    argv_emulation=False,
    target_arch=None,
)
