"""baseline

Revision ID: ce0c7c1d26e9
Revises: 
Create Date: 2026-05-25 19:07:18.259822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0c7c1d26e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hint', sa.String(length=500), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('learning_goal', sa.String(length=500), nullable=False),
    sa.Column('coach_line', sa.String(length=500), nullable=False),
    sa.Column('starter_tip', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('original_username', sa.String(length=50), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_reason', sa.String(length=200), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('bg', sa.String(length=10), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('ranking_metric', sa.String(length=30), nullable=False),
    sa.Column('question_unit_ids', sa.String(length=500), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('countdown_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('battle_time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('battle_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battle_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battle_answer_accept_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('power_score', sa.Integer(), nullable=False),
    sa.Column('max_combo', sa.Integer(), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('extreme_passes', sa.Integer(), nullable=False),
    sa.Column('extreme_dual_passes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('level_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('best_combo', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level_id', name='uq_user_level')
    )
    op.create_index(op.f('ix_level_progress_user_id'), 'level_progress', ['user_id'], unique=False)
    op.create_table('play_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('play_session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('pvp_room_id', sa.Integer(), nullable=True),
    sa.Column('best_combo', sa.Integer(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['pvp_room_id'], ['pvp_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_sessions_play_session_id'), 'play_sessions', ['play_session_id'], unique=True)
    op.create_index(op.f('ix_play_sessions_pvp_room_id'), 'play_sessions', ['pvp_room_id'], unique=False)
    op.create_index(op.f('ix_play_sessions_user_id'), 'play_sessions', ['user_id'], unique=False)
    op.create_table('pvp_broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['pvp_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_room_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_order', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=20), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('live_battle_power', sa.Integer(), nullable=False),
    sa.Column('live_correct_count', sa.Integer(), nullable=False),
    sa.Column('live_wrong_count', sa.Integer(), nullable=False),
    sa.Column('live_answered_count', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_answer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['pvp_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_pvp_room_member')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.Column('knowledge_meaning', sa.String(length=1000), nullable=False),
    sa.Column('knowledge_rule', sa.String(length=1000), nullable=False),
    sa.Column('knowledge_error', sa.String(length=1000), nullable=False),
    sa.Column('knowledge_example', sa.String(length=1000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_review_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('play_session_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_review_decisions_play_session_id'), 'score_review_decisions', ['play_session_id'], unique=False)
    op.create_index(op.f('ix_score_review_decisions_user_id'), 'score_review_decisions', ['user_id'], unique=False)
    op.create_table('answer_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('play_session_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('question_version', sa.Integer(), nullable=False),
    sa.Column('correct_answer_snapshot', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('play_session_id', 'question_id', name='uq_session_question')
    )
    op.create_index(op.f('ix_answer_records_created_at'), 'answer_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_answer_records_is_correct'), 'answer_records', ['is_correct'], unique=False)
    op.create_index(op.f('ix_answer_records_play_session_id'), 'answer_records', ['play_session_id'], unique=False)
    op.create_index(op.f('ix_answer_records_question_id'), 'answer_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_records_user_id'), 'answer_records', ['user_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('play_session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('play_session_id', 'question_id', name='uq_sq_session_question'),
    sa.UniqueConstraint('play_session_id', 'question_order', name='uq_sq_session_order')
    )
    op.create_index(op.f('ix_session_questions_play_session_id'), 'session_questions', ['play_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_questions_play_session_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_answer_records_user_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_question_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_play_session_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_is_correct'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_created_at'), table_name='answer_records')
    op.drop_table('answer_records')
    op.drop_index(op.f('ix_score_review_decisions_user_id'), table_name='score_review_decisions')
    op.drop_index(op.f('ix_score_review_decisions_play_session_id'), table_name='score_review_decisions')
    op.drop_table('score_review_decisions')
    op.drop_table('questions')
    op.drop_table('pvp_room_members')
    op.drop_table('pvp_broadcasts')
    op.drop_index(op.f('ix_play_sessions_user_id'), table_name='play_sessions')
    op.drop_index(op.f('ix_play_sessions_pvp_room_id'), table_name='play_sessions')
    op.drop_index(op.f('ix_play_sessions_play_session_id'), table_name='play_sessions')
    op.drop_table('play_sessions')
    op.drop_index(op.f('ix_level_progress_user_id'), table_name='level_progress')
    op.drop_table('level_progress')
    op.drop_table('user_stats')
    op.drop_table('user_achievements')
    op.drop_table('pvp_rooms')
    op.drop_table('levels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('achievements')
    # ### end Alembic commands ###
